module.exports =
[ 'Bedfordshire'
, 'Berkshire'
, 'Bristol'
, 'Buckinghamshire'
, 'Cambridgeshire'
, 'Cheshire'
, 'Cleveland'
, 'Cornwall'
, 'County Durham'
, 'Cumbria'
, 'Derbyshire'
, 'Devon'
, 'Dorset'
, 'East Riding of Yorkshire'
, 'East Sussex'
, 'Essex'
, 'Gloucestershire'
, 'Greater London'
, 'Greater Manchester'
, 'Hampshire'
, 'Herefordshire'
, 'Hertfordshire'
, 'Isle of Wight'
, 'Isles of Scilly'
, 'Kent'
, 'Lancashire'
, 'Leicestershire'
, 'Lincolnshire'
, 'Merseyside'
, 'Middlesex'
, 'Norfolk'
, 'North Yorkshire'
, 'Northamptonshire'
, 'Northumberland'
, 'Nottinghamshire'
, 'Oxfordshire'
, 'Rutland'
, 'Shropshire'
, 'Somerset'
, 'South Yorkshire'
, 'Staffordshire'
, 'Suffolk'
, 'Surrey'
, 'Tyne & Wear'
, 'Warwickshire'
, 'West Midlands'
, 'West Sussex'
, 'West Yorkshire'
, 'Wiltshire'
, 'Worcestershire'
]
