module.exports =
[ 'Aberdeenshire'
, 'Angus'
, 'Argyll & Bute'
, 'Ayrshire'
, 'Banffshire'
, 'Berwickshire'
, 'Borders'
, 'Caithness'
, 'Clackmannanshire'
, 'Dumfries & Galloway'
, 'Dunbartonshire'
, 'Dundee'
, 'East Ayrshire'
, 'East Dunbartonshire'
, 'East Lothian'
, 'East Renfrewshire'
, 'Edinburgh'
, 'Falkirk'
, 'Fife'
, 'Highland'
, 'Inverclyde'
, 'Kincardineshire'
, 'Lanarkshire'
, 'Midlothian'
, 'Moray'
, 'North Ayrshire'
, 'North Lanarkshire'
, 'Orkney'
, 'Perth & Kinross'
, 'Renfrewshire'
, 'Scottish Borders'
, 'Shetland'
, 'South Ayrshire'
, 'South Lanarkshire'
, 'Stirlingshire'
, 'West Dunbartonshire'
, 'West Lothian'
, 'Western Isles'
]
